### PR TITLE
0.3.2

### PR DESCRIPTION
**Pull request by Ghawken**
One option?

Basically add a action item - "use Standard Indigo Commands"
& capture this early - and run turnon, turnoff, and TurnOn/TurnOff depending on setbrightness levels

Minimal code.
Not sure the clearness of the 'use standard indigo commands' though.

Welcome to close the Pull - more did as way of sharing item.

### CODE REVIEW

**Comment by FlyingDiver** [comment]
Can't use this, it breaks all the existing Masquerade devices.

**Comment by Ghawken** [comment]
Not sure that is the case?  Mine run fine.

It only runs if ‘use standard indigo commands’ selected in action selection.  Otherwise everything untouched.

**Comment by FlyingDiver** [comment]
Oh, I missed how you structured the logic.  Hmmm.

**Comment by Ghawken** [comment]
Yeah - more an example than anything.  

Many ways to skin a cat, and we all seem to skin differently! 

Think it does need a lower level approach to access the turn on, turn off indigo device controls.  Would also be a backup, selectable approach for custom devices for plugins if all fails - could access the turn on, turn off.

But reference cat comment above!

**Comment by FlyingDiver** [comment]
Oops.  I was intending to merge that into a new branch, but my client merged it into master.  Now I need to figure out how to undo that.

**Pull request merged**
